const productCategories = require('../../constants/productCategories.js');
const CustomError = require('../../error-handling/customError.js');
const generateAiResponse = require('../aiChat.js');
const { isPlainObject } = require('../helpers/object.js');

async function generateProductFieldsAi(prods=[], fieldsToAutoGenerate) {

    if(prods.length === 0)
        throw new CustomError(
    'BadRequestError', 'Product name is required for generating description', 400);
    
    const products = await generateAiResponse(
`Add only the following field(s): ${fieldsToAutoGenerate.join(', ')}. 
Generate creative values for each product.

Rules:
1. 'description' – maximum 500 characters are allowed. (If included in fields above)
2. 'tags'[] – maximum 10 tags are allowed. (If included in fields above)
3. 'subcategory' must be included.
4. Subcategory must be chosen from: ${JSON.stringify(productCategories)}.
5. If any product seems like a spam or invalid grocery by its name, respond with JSON {error: "true"}

Respond ONLY with valid JSON[] for products.. no plain objects, No explanations, no text outside JSON.

Products: ${JSON.stringify(prods)}`)

    const parsed = products ? JSON.parse(products): '';

    if (parsed && ['true', true].includes(parsed.error)) {
        throw new CustomError(
            'BadRequestError',
            'Invalid product data or spam detected by AI. Please provide valid grocery products.',
            400);
    }

    if(isPlainObject(prods)) 
        prods = [prods]


    // server error
    if(!parsed || parsed.length !== prods.length){
        throw new Error('Failed to generate product fields. Please try again.')
    }

    console.log('Products generated by AI: ', parsed);

    return parsed;
}

module.exports = generateProductFieldsAi;